version: "3.3"

services:
  dashboard:
    image: ghcr.io/naiba/nezha-dashboard
    restart: always
    volumes:
      - ./data:/dashboard/data
      - ./static-custom/static:/dashboard/resource/static/custom:rw
      - ./theme-custom/template:/dashboard/resource/template/theme-custom:rw
      - ./dashboard-custom/template:/dashboard/resource/template/dashboard-custom:rw
    ports:
      - 80:80
      - 5555:5555
